### ISSUE TITLE
Two licenses? CC0-1.0 and GPL-2

### ISSUE THREAD

**Issue by romildo** [darkomarko42/Marwaita#1]
First let me thank you for publishing your themes as git repositories. This will help packaging them for [NixOS](https://nixos.org) (and other Linux distributions as well).

Better yet would be to have released or tagged versions. It can be seen that they are versioned on https://www.pling.com/p/1239855/

There are two different license in the repository: CC0-1.0 (at the top level directory) and GPL-2 (in the theme directories). Are both applicable?

**Comment by darkomarko42** [comment]
i fix the licenses :) is GPL3
