### ISSUE TITLE
Large black border on some windows (those with CSD?)

### ISSUE THREAD

**Issue by symphorien** [darkomarko42/Marwaita#10]
with marwaita 9.1, some windows have large black border:
this dialog in libreoffice: 

![image](https://user-images.githubusercontent.com/12595971/117715769-41c5f500-b1c8-11eb-9b57-5e53b5668e2e.png)

the file selection dialog

![image](https://user-images.githubusercontent.com/12595971/117715899-6f12a300-b1c8-11eb-91ec-36561ff8af31.png)

evince

![image](https://user-images.githubusercontent.com/12595971/117715966-83ef3680-b1c8-11eb-850f-de4dfa898ab6.png)

And xfce's settings panel
![image](https://user-images.githubusercontent.com/12595971/117716073-a84b1300-b1c8-11eb-8553-549d38e1a9c5.png)

But many windows are just fine. I suppose that the black border is only on windows which request CSD

Infos: XFCE on NixOS 21.05

**Comment by symphorien** [comment]
still present in 9.2.1

**Comment by symphorien** [comment]
Still present in 9.5:
![image](https://user-images.githubusercontent.com/12595971/124395774-7d2afe80-dcf5-11eb-9211-54e1a6f02d65.png)

**Comment by darkomarko42** [comment]
you gotta understand that the theme is meant to be used on budgie desktop. turn on the composition on xfce or delete the "DECORATION" lines on the .css file

**Comment by symphorien** [comment]
Strange, I have a compositor running (picom).
