### ISSUE TITLE
 Header bar font size of some apps are a bit too small

### ISSUE THREAD

**Issue by Master811129** [darkomarko42/Marwaita#13]
![Screenshot from 2021-08-15 22-02-58](https://user-images.githubusercontent.com/37829730/129487279-e72efa59-e90c-44fe-a264-cb48830a3d0e.png)

**Comment by darkomarko42** [comment]
thats is the exact same size of adwaita theme(the theme base for gtk apps) :)

**Comment by Master811129** [comment]
@darkomarko42 Please take a look at this screenshot for a better comparison I'm still thinking the font size way smaller than Adwaita.
![Screenshot from 2021-08-19 23-12-03](https://user-images.githubusercontent.com/37829730/130127360-88e0e537-75de-4a13-9170-d8c4375d71fe.png)

I think there is some problem for borderless headerbars.

the old headerbars are OK: (see the screenshot below fonts are OK):
![Screenshot from 2021-08-19 23-24-42](https://user-images.githubusercontent.com/37829730/130128717-8b188241-4e41-42c5-8c46-acb59f7cba41.png)
