### ISSUE TITLE
Font in Modern-Style headerbars is tiny

### ISSUE THREAD

**Issue by FreeFight3r** [darkomarko42/Marwaita#14]
## Bug Report

Hi it seems that this theme makes modern (not old ones) headerbar options too tiny I don't have this problem in adwaita or any other compact themes. See the screenshots:

## Reproduce
- Install any modern styled headerbar apps (For example official gnome weather)
-  see the issue

Adwaita Theme:
![Screenshot from 2021-09-02 20-06-55](https://user-images.githubusercontent.com/89989439/131874306-2ad9f3ea-d755-4085-b61b-984f4900454f.png)
Orchis-compact theme:
![Screenshot from 2021-09-02 20-07-56](https://user-images.githubusercontent.com/89989439/131874439-6c0c90da-1811-442e-aefb-d9c3a3aefeff.png)
This theme:
![Screenshot from 2021-09-02 20-05-19](https://user-images.githubusercontent.com/89989439/131874524-74a9cdb9-5434-43da-8e1f-853cbd50a4f0.png)

**Comment by darkomarko42** [comment]
i had to reduce the size of these text because the theme use less padding on the widgets like buttons and text entries

**Comment by Master811129** [comment]
@darkomarko42 
it's exactly my point in #13 I hope you fix this issue.
