### ISSUE TITLE
Problems with Cinnamon.

### ISSUE THREAD

**Issue by jairoraiol** [darkomarko42/Marwaita#15]
1- In Nemo, there is no effect when hovering over the folder names in the sidebar.

2- In warning and configuration windows, such as About the Program, the window close button in the title bar is not provided. This is important because not all windows contain the close button.

3- In LibreOffice 7.2.3.2, the options selected in the menu strip are not marked. An example of this is the text alignment options. So there is no way to know which options were chosen. There is also no effect when hovering over the options.

Distribution: Linux Mint 20.2 Cinnamon 64bit.
Cinnamon Version: 5.0.7

I really like this theme.
Great job.

Thanks!

**Comment by darkomarko42** [comment]
check out the new version ;)
