### ISSUE TITLE
round sets of buttons don't render well

### ISSUE THREAD

**Issue by symphorien** [darkomarko42/Marwaita#3]
Here is a screenshot of the toolbar of paperwork with adwaita and marwaita:
![image](https://user-images.githubusercontent.com/12595971/87231866-245aab80-c3aa-11ea-8e94-f65e38469ddb.png)

![image](https://user-images.githubusercontent.com/12595971/87231848-08570a00-c3aa-11ea-8a90-a0c07b38b427.png)

As you can see round sets of buttons don't render correctly with marwaita.

**Comment by darkomarko42** [comment]
sorry for the delay. i took a look of it and the app uses his own css file. fix the separation between the buttons and add borders to the buttons :)

**Comment by symphorien** [comment]
do I understand correctly that it's not fixable then ?

**Comment by darkomarko42** [comment]
![Captura de pantalla de 2020-08-11 09-08-10](https://user-images.githubusercontent.com/28841389/89895468-3ea6c580-dbb2-11ea-841b-04a6c29cc6fc.png)

this is how it looks after (the borders on the left cant be remove)

**Comment by darkomarko42** [comment]
i will update the files soon, now im working on it :)

**Comment by symphorien** [comment]
Did you forget to push the changes ?

**Comment by darkomarko42** [comment]
i have like a schedule, every two days i update something to pling.org :)

**Comment by darkomarko42** [comment]
the new version is up

**Comment by symphorien** [comment]
Awesome thanks!
