### ISSUE TITLE
Is old version available?

### ISSUE THREAD

**Issue by VentGrey** [darkomarko42/Marwaita#6]
Hello, sorry for the hour. I was wondering if there is still a copy of a very old version of this theme back to when it used to look like this:

![image](https://user-images.githubusercontent.com/24773698/103745801-b93f0a00-4fc5-11eb-9944-9aa3800af7cb.png)

I have been searching through the GitHub history but the changes are not that back. I would kindly appreciate if you could give me some direction in this. Thanks in advance :sweat_smile:

**Comment by darkomarko42** [comment]
you should search on the "archived" section of the pling.com page of marwaita ( https://www.pling.com/p/1239855/ ) or try another of my themes nexto ( https://www.pling.com/p/1404891/ ) :)

**Comment by darkomarko42** [comment]
deberias probar en la seccion de "archived" en la pagina de pling de marwaita ( https://www.pling.com/p/1239855/ ) o prueba con otro tema mio "Nexto" ( https://www.pling.com/p/1404891/ ) :)

**Comment by VentGrey** [comment]
Ya lo encontré era a mediados de 2019 :) 
Muchas gracias por tu apoyo :cat:
