### ISSUE TITLE
Help editing CSS for minor change

### ISSUE THREAD

**Issue by superdreamkilla** [darkomarko42/Marwaita#8]
Hello, I would like to know what CSS file I need to edit to give Marwaita light blue bars. This is needed to benefit my workflow with Gimp Do you think you can give me instructions on how to edit Marwaita's CSS. Thanks

pic related. 
![image](https://user-images.githubusercontent.com/61440491/105643262-a9a93780-5e86-11eb-832c-80f520ad01c6.png)

**Comment by darkomarko42** [comment]
fix :)
